name: build-runners

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PWD }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.1.0
        with:
          context: ./runner/terraform
          file: ./runner/terraform/dockerfile
          platforms: linux/amd64
          tags: "${{ secrets.DOCKER_USR }}/tcrterraform:latest"
          push: true
