name: build-runners

on:
  push:
    branches: [ master ]

jobs:

  core:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push Docker image - runner
        uses: docker/build-push-action@v2.1.0
        with:
          context: ./container/_core/runner
          file: ./container/_core/runner/Dockerfile
          platforms: linux/amd64
          tags: markusheiliger/tcrunner:latest
          push: true

  runner:
    needs: core
    runs-on: ubuntu-latest
    strategy:
      matrix:
        max-parallel: 5
        runner: ['arm', 'terraform']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push Docker image - arm
        uses: docker/build-push-action@v2.1.0
        with:
          context: ./container/${{ matrix.runner }}
          file: ./container/${{ matrix.runner }}/Dockerfile
          platforms: linux/amd64
          tags: markusheiliger/tcrunner-${{ matrix.runner }}:latest
          push: true

          
